name: Deploy

# on: push
on: workflow_dispatch

concurrency:
  group: deploys
  cancel-in-progress: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: deploy
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install
        run: bun install --save

      - name: Build
        run: bun run build

      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          directory: dist
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: projektarbeit
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}